### ISSUE TITLE
Review: Cotton Energy First Draft

### ISSUE THREAD

**Issue by LemmaEOF** [CottonMC/cotton-energy#1]
I just pushed the [first draft of the energy API](https://github.com/CottonMC/cotton-energy/commit/c98466bb5017711f2d9f888d958b2f2785fecd8f). It still needs a proper name, but I wanna get people's thoughts:

- Is the API missing anything major? Is it clear enough what it does?
- Do any methods need to be renamed? Is anything confusing?
- Are the packet sizes good? Do they need to be re-adjusted?
- Do the javadocs make sense? Is there anything missing from them?

**Comment by Frontrider** [comment]
packet tier should NOT be an enum. That is bad design and makes it impossible to extend the system in any way, without hacking it.

**Comment by strikerrocker** [comment]
Rename `getCurrentCharge`to `getCurrentEnergy`

**Comment by Ansraer** [comment]
I would suggest splitting up the interface. Makes it cleaner and easier to use if you don't have to implement a mega interface.

I also wouldn't hardcoded packet size. Haven't looked at much more than the interface, but can't you make package size a dynamic float value?

**Comment by LemmaEOF** [comment]
> packet tier should NOT be an enum. That is bad design and makes it impossible to extend the system in any way, without hacking it.

> I also wouldn't hardcoded packet size. Haven't looked at much more than the interface, but can't you make package size a dynamic float value?

I'm trying to avoid having the system get hyper-inflated instantly. Limiting the packet sizes means there's a limit on how inflated things can get, and lets us better design an actually fun and engaging system.

**Comment by Pannoniae** [comment]
Something similar to an API has been merged.
