### ISSUE TITLE
List of things I noticed

### ISSUE THREAD

**Issue by Ansraer** [CottonMC/cotton-energy#9]
- [ ] Packet accepts any value, even if it's larger or smaller than the types min/max values. IMO it should be capped to the max value and be set to 0 if the value is smaller than the min value. All unused energy should be returned to whoever tried to set it.

- [ ] Energystorage has a int getCurrentEnergy() method that returns the amount of the blocks primary energy type and a EnergyType getPrimaryEnergyType method. I would suggest that we replace them with a Map<EnergyType, Integer>. This would allow one block to store multiple kinds of energy. (e.g. A battery that can store different Voltages)

**Comment by LemmaEOF** [comment]
We need to focus more on the first one in implementation than in the API itself. The second one is also mostly implementation, since you can't really put variables in an interface. I think we should maybe add a method for getting energy by type, and let implementation do what they want for storing everything.

**Comment by falkreon** [comment]
I don't know what you're talking about with Packet - we've dispensed with first-class Packets and if there's a class lying around for that still we should kill it. *edit: This is from December, so it's probably just still here from when Packets were a thing. I'm trying to close out old issues :)*

A battery doesn't have shelves that it puts different energy voltages into. There's a chemical reaction at the anode that yields free electrons. Voltage is just the difference in electric potential between the anode and the other end of the electric circuit, it'll always be the same (except irl as the anode is exhausted the potential drops, this is how we measure battery fullness)

We can skip a lot of those mechanics when they're easier and more fun for players, and better match what players expect out of a battery. So we'd have to apply those tests to storing multiple voltage types:

**simplicity test**:
Storing multiple voltage types in a block is more complicated than storing one voltage type.

**fun test**:
This is subjective, but I feel like this will require multiple bars or gauges on one battery, and perhaps even managing different power caps for each type. It seems awfully fussy and un-fun.

**user expectations test**:
Let's say we have a battery that we're filling with MV. An LV grinder sits next to the battery's output face, so the battery will push energy into it. If the battery has different shelves, then its MV shelf is full and its LV shelf is empty. The grinder remains powered down.

My expectations, generally, are that it's an MV battery, it will accept all MV and LV power and convert it to MV, and it will present MV to any consumer. This will result in the LV grinder frying; or, it's an LV battery, and as we try to push MV into it, it fries. Eventually if not addressed, explodes. The grinder remains powered down.

**Comment by falkreon** [comment]
The codebase has changed enough that these issues might actually be solved now. An energy component could potentially handle multiple types, but has a primary type. Multiple components can be provided to LibBlockAttributes to *advertise* those multiple types. Information is exposed on whether types can be freely converted and which types will be harmful to the component.

The default implementation now does type conversions when possible, calculates harm, and enforces minimum and maximum transfer sizes. So we've kind of accidentally wrapped this one up :)
